
title:
  "ClickClock"
  
description:
  "Cloud-based Clock
  
github:
  "ClickClockCC"

theme:
  jekyll-theme-cayman
  
permalink:
  pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
